# Generated by Django 5.2.1 on 2025-05-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='descount',
            new_name='discount',
        ),
    ]
